name: destroy
on:
  workflow_dispatch:

env:
  AZ_RG: rg-demo

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete resource group
        run: az group delete --name $AZ_RG --yes --no-wait